### PR TITLE
Apply material styles to Enable HC button

### PR DESCRIPTION
**Pull request by Hughp135**
**Why**
The "Enable/Disable HC" button looks sorta bad, so I applied some material styles to it

**Changes**
Added CSS copied from https://codepen.io/finnhvman/pen/MQyJxV (but slightly modified) to the button

**Screenshots**
Before changes:
image

After changes:
(see latest comments for updated screenshots)

### CODE REVIEW

**Comment by KentoNishi** [comment]
it needs to be less wide, otherwise it can overflow the entire top bar into 2 lines on small screens. maybe remove some padding

**Comment by Hughp135** [comment]
> it needs to be less wide, otherwise it can overflow the entire top bar into 2 lines on small screens. maybe remove some padding

How do you reproduce this? Even on the smallest possible size (1017px) it still fits onto one line for me (on desktop)

image

**Comment by KentoNishi** [comment]
use multi-view on holodex or holotools

**Comment by Hughp135** [comment]
In this case, i propose 2 options:

Smaller padding/text: 
image

Text only button:
image
Text only (hover):
image
Text only (dark):
image

**Comment by Hughp135** [comment]
Have gone with the smaller blue button for now, lmk if you prefer the text-only button

**Comment by r2dev2** [comment]
The text-only button looks so much better as it doesn't introduce a big blue rectangle on youtube's gray or white chat box.

**Comment by KentoNishi** [comment]
idea: a toggle or checkbox that just says "HyperChat"

that way we can avoid putting "enable" or "disable" altogether

idk how you did material design for this so can u try using a switch or checkbox and see how it looks?

**Comment by Candygoblen123** [comment]
A toggle or checkbox wouldn't work because we're effectively loading a new page.  Checkboxes and toggles are reactive, so loading a new page page won't work with them.  

For example: Microsoft uses a button for "Return to Classic SharePoint" because they have to load a new page to get there.

**Comment by Hughp135** [comment]
> idea: a toggle or checkbox that just says "HyperChat"
> 
> that way we can avoid putting "enable" or "disable" altogether
> 
> idk how you did material design for this so can u try using a switch or checkbox and see how it looks?

I've created a mockup of how that might look:

image

What u guys think?



> A toggle or checkbox wouldn't work because we're effectively loading a new page. Checkboxes and toggles are reactive, so loading a new page page won't work with them.
> 
> For example: Microsoft uses a button for "Return to Classic SharePoint" because they have to load a new page to get there.

Not sure why it wouldn't be possible - in this case we're just chaing the icon on the button depending on what state the app is in (enabled = ticked, disabled = not ticked).

**Comment by KentoNishi** [comment]
i dig the bottom one without the outline

**Comment by Hughp135** [comment]
logo idea

image

**Comment by Hughp135** [comment]
Implementation:

(When hyperchat is enabled)
image
(When hyperchat is disabled)
image

**Comment by Hughp135** [comment]
note to self: need to fix colors for dark theme

**Comment by Hughp135** [comment]
After fixing for dark theme:
image
image

image
image

**Comment by KentoNishi** [comment]
gonna put it here so we don't forget

* center text in tooltip
* improve logo visibility for dark mode
* update the update message

**Comment by Hughp135** [comment]
Going with a borderless button, looks a lot more natural in the context of youtube
image
image
image

**Pull request merged**
